name: KB Release
on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - run: pip install pandas
      - run: python kb_ci_runner.py --bundle

      - name: Grab bundle path
        id: bundle
        shell: bash
        run: |
          B=$(ls -1t kb_export/bundle/udigit_kb_site_bundle_*.zip | head -n1)
          echo "path=$B" >> $GITHUB_OUTPUT
          echo "name=$(basename "$B")" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: kb-${{ github.run_number }}
          name: KB Build ${{ github.run_number }}
          files: ${{ steps.bundle.outputs.path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
