name: Validate KB JSON
on:
  push:
    branches: [ main, master ]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Check JSON syntax
        run: |
          jq . kb/registry.json >/dev/null
          jq . kb/cross_links.json >/dev/null
          jq . kb/search.json >/dev/null
